#!/usr/bin/env python3
"""Generate requirements-app-lock.txt from the LIVE working environment.

Walks the installed dependency closure of the app stack and pins every
package at exactly the version running here. The Docker builds install this
lock with --no-deps, replicating the validated environment verbatim instead
of re-resolving it -- necessary because the working combination violates
some declared metadata (exojax 2.2.3 pins numpy<2 while the validated env
runs numpy 2.0.2), so pip's resolver rejects a combination that is proven
to work.

Run in the environment that runs the tool, then commit the lock:
    python deploy/make_app_lock.py
"""
from importlib.metadata import PackageNotFoundError, distribution
from pathlib import Path

from packaging.requirements import Requirement

# Roots: the three local packages' dependencies get walked, plus the gui
# extra (streamlit/pandas) and the Space bootstrap's huggingface_hub.
# v18: picaso + the runtime imports its metadata does NOT declare (measured
# by the 2026-07-20 import trace: synphot/stsynphot/virga/bokeh/xarray and
# friends are imported at picaso.justdoit import time but only partially
# declared) -- the trace is the authority, the walker fills in versions.
ROOTS = ["vulcan-jwst-tool", "vulcan-retrieval", "vulcan-jax",
         "streamlit", "pandas", "huggingface_hub", "matplotlib",
         "picaso", "synphot", "stsynphot", "virga-exo", "bokeh", "xarray",
         "photutils", "pooch", "sortedcontainers", "cloudpickle",
         "Bottleneck", "cftime", "crc32c", "defusedxml", "miepython",
         "platformdirs", "setuptools", "threadpoolctl", "zstandard",
         "xyzservices"]
# (jaraco.collections/jaraco.text are setuptools-vendored, not standalone
# distributions -- pinning setuptools covers them)
# Local editables: present in the closure but installed from the repo
# checkouts by the Dockerfile, never from PyPI.
LOCAL = {"vulcan-jwst-tool", "vulcan-retrieval", "vulcan-jax"}

seen: set[str] = set()
pins: dict[str, str] = {}


def canon(name: str) -> str:
    return name.lower().replace("_", "-")


def walk(name: str) -> None:
    c = canon(name)
    if c in seen:
        return
    seen.add(c)
    try:
        dist = distribution(name)
    except PackageNotFoundError:
        return                     # optional/extra dep not installed here
    if c not in LOCAL:
        pins[canon(dist.metadata["Name"])] = dist.version
    for raw in dist.requires or []:
        req = Requirement(raw)
        if req.marker is not None:
            # Evaluate WITHOUT platform context is not possible; evaluate
            # for this platform and additionally keep linux-relevant deps:
            # the only direction that matters here is mac-excluded/linux-
            # needed, which is rare -- flag candidates loudly instead.
            try:
                if not req.marker.evaluate({"extra": ""}):
                    m = str(req.marker)
                    if "linux" in m:
                        print(f"NOTE: skipped linux-marked dep {req.name} "
                              f"({m}) -- verify it is not needed")
                    continue
            except Exception:  # noqa: BLE001 -- keep going, pin what we can
                pass
        walk(req.name)


for r in ROOTS:
    walk(r)

out = Path(__file__).resolve().parent / "requirements-app-lock.txt"
lines = [
    "# GENERATED by make_app_lock.py from the validated working env.",
    "# Installed with --no-deps: versions are exact, resolver is bypassed",
    "# (the working set violates exojax's declared numpy<2 -- see the",
    "# generator's docstring). Regenerate after any env change.",
]
lines += [f"{n}=={v}" for n, v in sorted(pins.items())]
out.write_text("\n".join(lines) + "\n")
print(f"wrote {out} ({len(pins)} pins)")
